### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by robkooper**

### CODE REVIEW

**Review by asaxton — APPROVED** [review]

**Review by abodeuis — COMMENTED** [review]
Proofread it, Updates look good. Only suggestion would be to maybe add a little text on how to view log files in case something goes wrong

**Review by abodeuis — APPROVED** [review]

**Comment by craigsteffen** [comment]
Is the target audience someone who's never run this before?  I can understand the explanation because I know what all these things are, but for a new user, I think the text needs to be tweaked.  

What's the time scale for releasing this?  Is this something that MITRE needs to test our stuff now, or part of our overall rollout improving stuff over the next 6 months?

**Comment by craigsteffen** [comment]
@asaxton 

Is the target audience someone who's never run this before? I can understand the explanation because I know what all these things are, but for a new user, I think the text needs to be tweaked.

What's the time scale for releasing this? Is this something that MITRE needs to test our stuff now, or part of our overall rollout improving stuff over the next 6 months?

**Comment by asaxton** [comment]
@craigsteffen The initial audience is MITRE who will be running the entire stack on a single AWS EC2 instance with a GPU. They will be running it just for evaluation purposes.


This PR I would like to release ASAP. Over the next 6 month as MITRE and USGS become more "advanced users", we can fill in more details in the README using any feedback we get from MITRE and/or USGS.

**Comment by craigsteffen** [comment]
Ok.  If it's critical to release immediately, I have no objections.  MITRE presumably knows enough about the structure, and if they don't understand something, they can ask.  

As an example of one of the things that I think need work: Trying to think about the description from the point of view of someone who doesn't know how the system goes together, the statement 
"rabbitmq: The orchestrator of all the work" is misleading.  It's the message passing fabric that carries all the communication, but it doesn't orchestrate anything itself.  It's a communications library and a queue state machine.

**Review by craigsteffen — APPROVED** [review]
As technical description, I have no objections.  

I think the wording needs fleshing out to make it more explanatory for people who don't know the system.

**Pull request merged**
